my_list=['scooter','bicycle','car','train','plane']
print(my_list)
print(my_list[0])
print(my_list[-1])
print(my_list[2:])
my_list[2]='metro'
print(my_list)
my_dict={'scooter':'самокат','bicycle':'велосипед','car':'автомобиль','train':'поезд','plane':'самолет'}
print(my_dict)
print(my_dict['car'])
my_dict['car']='лимузин'
print(my_dict)